# permissions for end users to edit typesenseclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: typesensecluster-editor-role
rules:
- apiGroups:
  - ts.opentelekomcloud.com
  resources:
  - typesenseclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ts.opentelekomcloud.com
  resources:
  - typesenseclusters/status
  verbs:
  - get
