# permissions for end users to view typesenseclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: typesensecluster-viewer-role
rules:
- apiGroups:
  - ts.opentelekomcloud.com
  resources:
  - typesenseclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ts.opentelekomcloud.com
  resources:
  - typesenseclusters/status
  verbs:
  - get
