apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: typesensecluster-sample
spec:
  replicas: 3
  storage:
    storageClassName: standard
#  cors:
#    enabled: false
